Demo_ASP_React/Controllers/SysMenuController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Demo_ASP_React.DTO_ETITY;
using Newtonsoft.Json;


namespace Demo_ASP_React.Controllers
{
    public class SysMenuController : Controller
    {
        // GET: SysMenu
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult GetMenuLeft()
        {
            //JObject json = null;
            var contentData = new List<MenuLeftEntity>();
            try
            {
                LibGetDataDB getdb = new LibGetDataDB();
                string responseString = getdb.getDataUrl("http://localhost:55028/getMenuLeft/getMenuLeft");

                //json = JObject.Parse(responseString);

                contentData = JsonConvert.DeserializeObject<List<MenuLeftEntity>>(responseString);
                //List<MenuLeftEntity> oMyclass = Newtonsoft.Json.JsonConvert.DeserializeObject<List<MenuLeftEntity>>(Jsonstring);

            }
            catch (Exception ex)
            {
                throw ex;
            }

            ViewBag.ListMenu = contentData;

            return PartialView("_GetMenuLeft", contentData);
        }
    }
}

Demo_ASP_React/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Dịch vụ công trực tuyến - Hà Nội</title>

    <link href="../../Assets/css/fonts.css" rel="stylesheet">
    <link rel="stylesheet" href="../../Assets/css/admin.css">
    <link rel="stylesheet" href="../../Assets/css/datetimepicker.css">
    <link rel="stylesheet" href="../../Assets/css/notify.css">
    <link rel="stylesheet" href="../../Assets/css/jstree.css">
    <link rel="stylesheet" href="../../Assets/css/loading.css">
    <link rel="stylesheet" href="../../Assets/css/select2.css">
    <link rel="stylesheet" href="../../Assets/css/plugins-admin.css">

    <link href="../../Assets/css/rodal.css" rel="stylesheet">
    <link href="../../Assets/css/custom.css" rel="stylesheet">
    <link href="../../Assets/css/Site.css" rel="stylesheet">
    <link href="../../Assets/css/jquery-confirm.min.css" rel="stylesheet">

    <link rel="stylesheet" href="../../Assets/css/bootstrap.min.css">

    <style>
        .navbar-nav > .user-menu > .dropdown-menu > li.user-header {
            height: 150px;
        }
    </style>
</head>
<body class="skin-blue sidebar-mini sidebar-mini-expand-feature" style="height: auto; min-height: 100%;">
    <div id="page" class="">
        <div class="wrap-site dashboard">
            <!-- Main Header -->
            <header class="main-header">

                <!-- Logo -->
                <a href="/" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini">
                        <img src="/Assets/images/logo-mini.png" alt="Logo">
                    </span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg">
                        <img src="/Assets/images/logo.png" alt="Logo">
                    </span>
                </a>

                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top nav_menu" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <ul class="nav navbar-nav navbar-nav-left">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu">
                            <!-- Menu toggle button -->

                            <ul class="dropdown-menu">
                                <li class="header">You have 4 messages</li>
                                <li>
                                    <!-- inner menu: contains the messages -->
                                    <ul class="menu">
                                        <li>
                                            <!-- start message -->
                                            <a href="#">
                                                <div class="pull-left">
                                                    <!-- User Image -->
                                                    <img src="/Assets/images/user.jpg" class="img-circle" alt="User Image">
                                                </div>
                                                <!-- Message title and timestamp -->
                                                <h4>
                                                    Support Team
                                                    <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                                </h4>
                                                <!-- The message -->
                                                <p>Why not buy a new awesome theme?</p>
                                            </a>
                                        </li>
                                        <!-- end message -->
                                    </ul>
                                    <!-- /.menu -->
                                </li>
                                <li class="footer"><a href="#">See All Messages</a></li>
                            </ul>
                        </li>
                        <!-- /.messages-menu -->
                        <!-- Notifications Menu -->
                        <li class="dropdown notifications-menu">
                            <!-- Menu toggle button -->

                            <ul class="dropdown-menu">
                                <li class="header">You have 10 notifications</li>
                                <li>
                                    <!-- Inner Menu: contains the notifications -->
                                    <ul class="menu">
                                        <li>
                                            <!-- start notification -->
                                            <a href="#">
                                                <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                            </a>
                                        </li>
                                        <!-- end notification -->
                                    </ul>
                                </li>
                                <li class="footer"><a href="#">View all</a></li>
                            </ul>
                        </li>
                    </ul>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img src="/Assets/images/user.jpg" class="user-image" alt="User Image">
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs">Dịch Vụ Công Test Tỉnh/Thành </span>
                                    <span><i class="fa fa-angle-down"></i></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header">
                                        <img src="/Assets/images/user.jpg" class="img-circle" alt="User Image">

                                        <p>
                                            Dịch Vụ Công Test Tỉnh/Thành

                                        </p>
                                    </li>
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="/Account/ChangePassword" class="btn btn-default btn-flat">Đổi mật khẩu</a>
                                        </div>

                                        <div class="pull-right">
                                            <a href="/Authentication/Logout" class="btn btn-default btn-flat">Thoát</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown messages-menu">
                                <!-- Menu toggle button -->

                                <ul class="dropdown-menu">
                                    <li class="header">You have 4 messages</li>
                                    <li>
                                        <!-- inner menu: contains the messages -->
                                        <ul class="menu">
                                            <li>
                                                <!-- start message -->
                                                <a href="#">
                                                    <div class="pull-left">
                                                        <!-- User Image -->
                                                        <img src="/Assets/images/user.jpg" class="img-circle" alt="User Image">
                                                    </div>
                                                    <!-- Message title and timestamp -->
                                                    <h4>
                                                        Support Team
                                                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                                    </h4>
                                                    <!-- The message -->
                                                    <p>Why not buy a new awesome theme?</p>
                                                </a>
                                            </li>
                                            <!-- end message -->
                                        </ul>
                                        <!-- /.menu -->
                                    </li>
                                    <li class="footer"><a href="#">See All Messages</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar" style="height: auto;">

                    <!-- Sidebar Menu -->
                    @{Html.RenderAction("GetMenuLeft", "SysMenu");}
                    <!-- /.sidebar-menu -->

                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">

             @RenderBody()

            </div>
            <!-- /.content-wrapper -->

            <div class="control-sidebar-bg"></div>

            <div class="modal mainmodal" id="myModal" role="document">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            <p>One fine body…</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary btn-save">Save changes</button>
                        </div>
                    </div>
                </div>
            </div><!-- /.modal -->

            <div id="loading" class="loading" style="background-color: #ddd; height: 100%; width: 100%; position: fixed; z-index: 9; margin-top: 0px; top: 0px; opacity: 0.7; display: none">
                <img style="position: absolute; left: 50%; top: 50%; width: 100px; height: 100px; margin-left: -50px; margin-top: -50px" src="/Content/Images/load2.gif">
            </div>
        </div><!-- box wrap site -->

        <script src="../../Assets/js/admin.js"></script>
        <script defer="" src="../../Assets/js/validate.js"></script>
        <script async="" src="../../Assets/js/datetimepicker.js"></script>
        <script src="../../Assets/js/custom.js"></script>
        <script src="../../Assets/js/mainJs.js"></script>

        @*<script async="" src="http://cdn.dvc.egov.com/libs/script/select2?version=1.0.1"></script>*@
        <script async="" src="../../Assets/js/jquery-number.js"></script>
        <script async="" src="../../Assets/js/jstree.js"></script>
        <script async="" src="../../Assets/js/notify.js"></script>
        <script async="" src="../../Assets/js/loading.js"></script>
        <script src="../../Assets/js/jquery-confirm.min.js"></script>

        @*<script src="/Scripts/bundles/vendor.bundle.js"></script>*@


        <!-- Chart -->
        <script src="../../Assets/js/highcharts.js"></script>
        <script src="../../Assets/js/exporting.js"></script>

        <script src="../../Assets/js/chart.js"></script>

        @RenderSection("scripts", required: false)

        <script>
            $(function () {
                window.OrganizationId = '728645E8745320D8E054000C29748FC6';
                var hContent = $(window).height() - ($(".nav_menu").height())-10;
                $('.box-menu-left').attr("style", "display: block;overflow:auto;height: " + hContent + "px !important");
            })
        </script>
    </div>

</body>


</html>

Demo_ASP_React/Views/Shared/_Layoutbk.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>